name: Docker – Build & Publish

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "*.*.*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/yourimage   # <— change
  PLATFORMS: linux/amd64,linux/arm64
  DOCKER_CONTEXT: .
  DOCKERFILE: ./Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read }

    steps:
      - uses: actions/checkout@v4

      - name: Check free space
        id: space
        run: |
          set -euo pipefail
          df -h /
          avail_mb=$(df -Pm / | awk 'NR==2{print $4}')
          echo "avail_mb=$avail_mb" >> "$GITHUB_OUTPUT"

      # Quick cleanup only if <15GB free; hard cap 3 minutes
      - name: Quick cleanup (capped)
        if: ${{ steps.space.outputs.avail_mb < 15000 }}
        timeout-minutes: 3
        run: |
          set -euxo pipefail
          # remove big toolchains fast; skip apt purges (slow)
          sudo rm -rf /usr/local/lib/android || true &
          sudo rm -rf /usr/share/dotnet || true &
          sudo rm -rf /opt/ghc || true &
          docker system prune -af || true
          wait || true
          df -h /

      - uses: docker/setup-qemu-action@v3

      - name: Set up Buildx (small GC budget)
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --oci-worker-gc --oci-worker-gc-keepstorage 6GB

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (PR: no push) / Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKER_CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # keep runner disk small
          provenance: false
          sbom: false
