name: Docker – Build & Publish

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "*.*.*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/yourimage   # <-- change
  PLATFORMS: linux/amd64,linux/arm64
  BUILD_CONTEXT_DIR: .        # <-- renamed (was DOCKER_CONTEXT) to avoid collision
  DOCKERFILE: ./Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Docker is running
        shell: bash
        run: |
          set -euo pipefail
          if ! command -v docker >/dev/null 2>&1; then
            curl -fsSL https://get.docker.com | sh
          fi
          sudo systemctl start docker || sudo service docker start || true
          # Defensive: if someone set DOCKER_CONTEXT in repo/org envs, drop it
          unset DOCKER_CONTEXT || true
          docker info >/dev/null

      - name: Check free space
        id: space
        shell: bash
        run: |
          set -euo pipefail
          df -h /
          avail_mb=$(df -Pm / | awk 'NR==2{print $4}')
          echo "avail_mb=$avail_mb" >> "$GITHUB_OUTPUT"

      - name: Quick cleanup
        if: ${{ fromJSON(steps.space.outputs.avail_mb) < 15000 }}
        timeout-minutes: 2
        shell: bash
        run: |
          set -euxo pipefail
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc || true
          docker system prune -af || true
          df -h /

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: "--oci-worker-gc --oci-worker-gc-keepstorage 6GB"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.BUILD_CONTEXT_DIR }}   # <-- use the renamed var
          file: ${{ env.DOCKERFILE }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
