name: Docker – Build & Publish

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "*.*.*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: docker.io/xasser/hashtovast
  PLATFORMS: linux/amd64,linux/arm64
  BUILD_CONTEXT_DIR: .
  DOCKERFILE: ./Dockerfile

jobs:
  build:
    # If you're on a self-hosted runner (your logs show actions-runner paths), keep this:
    runs-on: self-hosted
    # If you use GitHub-hosted instead, change to: runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Docker is running
        shell: bash
        run: |
          set -euo pipefail
          if ! command -v docker >/dev/null 2>&1; then
            curl -fsSL https://get.docker.com | sh
          fi
          sudo systemctl start docker || sudo service docker start || true
          # Avoid collision with Docker CLI context env
          unset DOCKER_CONTEXT || true
          docker info >/dev/null

      - name: Reset stale Buildx/BuildKit
        shell: bash
        run: |
          set -euo pipefail
          docker buildx ls >/dev/null 2>&1 || true
          for b in $(docker buildx ls 2>/dev/null | awk 'NR>1 {print $1}'); do
            docker buildx rm -f "$b" || true
          done
          docker ps -a --filter 'name=buildx_buildkit' -q | xargs -r docker rm -f || true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:v0.16.0
            network=host
          buildkitd-flags: "--oci-worker-gc --oci-worker-gc-keepstorage=6000"

      - name: Bootstrap builder
        shell: bash
        run: |
          set -euo pipefail
          docker buildx inspect --bootstrap
          docker buildx ls

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.BUILD_CONTEXT_DIR }}
          file: ${{ env.DOCKERFILE }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
